import type { StationId } from '../types';
import type { MachineAssetId, MachineTelemetry, StationDigitalTwinData } from '../types/digitalTwin';

/**
 * DAKSHIN — Digital Twin Asset Data
 *
 * NOTE: All maintenance records are marked with _demo: true.
 * Replace with real maintenance API responses during integration phase.
 *
 * Optional telemetry fields (operating_hours, voltage, flow_rate) are
 * included where plausible for the asset type.
 * Fields absent here will display as "Not available" in the UI.
 */
export const INITIAL_STATION_ASSETS: Record<StationId, Record<MachineAssetId, MachineTelemetry>> = {
  maitri: {
    'GEN-01': {
      asset_id: 'GEN-01',
      station_id: 'maitri',
      name: 'Primary Diesel Generator 01',
      asset_type: 'generator',
      status: 'WARNING',
      temperature: 82.4,
      vibration: 4.8,
      current: 74,
      power: 128,
      fuel: 72,
      efficiency: 82,
      failure_risk: 42,
      operating_hours: 3847,
      last_update: '12:27:12 UTC+5',
      possible_issue: 'Thermal elevation and slight vibration variance under base load',
      position: [-4.2, 1.2, -2.5],
      maintenance: {
        state: 'DUE',
        last_maintenance: '2026-07-15',
        next_maintenance: '2026-09-15',
        operating_hours: 3847,
        known_issue: 'Bearing temperature trending upward. Vibration amplitude 4.8 mm/s above threshold.',
        recommended_action: 'Inspect and replace main bearing assembly. Check cooling fan belt tension.',
        spare_parts: [
          { part_name: 'Main Generator Bearing', part_code: 'BRG-GEN-204', availability: 'AVAILABLE' },
          { part_name: 'Cooling Fan Belt 12V', part_code: 'BELT-FAN-12', availability: 'LOW_STOCK' },
        ],
        _demo: true,
      },
    },
    'GEN-02': {
      asset_id: 'GEN-02',
      station_id: 'maitri',
      name: 'Secondary Standby Generator',
      asset_type: 'generator',
      status: 'NORMAL',
      temperature: 44.1,
      vibration: 1.2,
      current: 0,
      power: 0,
      fuel: 94,
      efficiency: 98,
      failure_risk: 12,
      operating_hours: 1204,
      last_update: '12:27:12 UTC+5',
      possible_issue: undefined,
      position: [-4.2, 1.2, 2.5],
      maintenance: {
        state: 'NORMAL',
        last_maintenance: '2026-08-01',
        next_maintenance: '2026-11-01',
        operating_hours: 1204,
        recommended_action: 'Routine 3-month inspection on schedule.',
        _demo: true,
      },
    },
    'BAT-01': {
      asset_id: 'BAT-01',
      station_id: 'maitri',
      name: 'DC Battery Bank 48V',
      asset_type: 'battery',
      status: 'NORMAL',
      temperature: 19.5,
      vibration: 0.1,
      current: 38,
      power: 45,
      fuel: 88,
      efficiency: 96,
      failure_risk: 15,
      operating_hours: 6210,
      voltage: 48.4,
      last_update: '12:27:10 UTC+5',
      position: [-2.0, 0.8, -4.0],
      maintenance: {
        state: 'NORMAL',
        last_maintenance: '2026-06-20',
        next_maintenance: '2026-12-20',
        operating_hours: 6210,
        recommended_action: 'Cell capacity check recommended at 6-month interval.',
        _demo: true,
      },
    },
    'FUEL-01': {
      asset_id: 'FUEL-01',
      station_id: 'maitri',
      name: 'Arctic Aviation Turbine Fuel Tank',
      asset_type: 'fuel_system',
      status: 'NORMAL',
      temperature: -14.2,
      vibration: 0.2,
      current: 12,
      power: 8,
      fuel: 68,
      efficiency: 99,
      failure_risk: 8,
      last_update: '12:27:08 UTC+5',
      position: [-7.0, 0.9, 0],
      maintenance: {
        state: 'NORMAL',
        last_maintenance: '2026-05-10',
        next_maintenance: '2026-11-10',
        operating_hours: 0, // Tank — not powered
        recommended_action: 'Biannual tank integrity pressure test on schedule.',
        _demo: true,
      },
    },
    'PUMP-01': {
      asset_id: 'PUMP-01',
      station_id: 'maitri',
      name: 'Hydraulic Transfer Pump',
      asset_type: 'pump',
      status: 'WARNING',
      temperature: 58.2,
      vibration: 5.8,
      current: 28,
      power: 22,
      fuel: 100,
      efficiency: 76,
      failure_risk: 54,
      operating_hours: 2988,
      flow_rate: 48.2,
      last_update: '12:27:11 UTC+5',
      possible_issue: 'Impeller cavitation detected at sub-zero fluid transfer',
      position: [2.5, 0.8, -3.2],
      maintenance: {
        state: 'OVERDUE',
        last_maintenance: '2025-12-01',
        next_maintenance: '2026-06-01',
        operating_hours: 2988,
        known_issue: 'Impeller cavitation at sub-zero temperatures. Bearing noise at startup.',
        recommended_action: 'Replace impeller assembly. Inspect and re-grease shaft bearings.',
        spare_parts: [
          { part_name: 'Hydraulic Impeller Type-B', part_code: 'IMP-HYD-B', availability: 'AVAILABLE' },
          { part_name: 'Pump Shaft Bearing Kit', part_code: 'BRG-PMP-KIT', availability: 'AVAILABLE' },
          { part_name: 'Seal Ring Set P-12', part_code: 'SEAL-P12', availability: 'LOW_STOCK' },
        ],
        _demo: true,
      },
    },
    'HEATER-01': {
      asset_id: 'HEATER-01',
      station_id: 'maitri',
      name: 'Central Habitat Heat Exchanger',
      asset_type: 'hvac',
      status: 'NORMAL',
      temperature: 21.2,
      vibration: 0.8,
      current: 44,
      power: 65,
      fuel: 100,
      efficiency: 94,
      failure_risk: 18,
      operating_hours: 8741,
      last_update: '12:27:12 UTC+5',
      position: [1.8, 1.4, 2.0],
      maintenance: {
        state: 'NORMAL',
        last_maintenance: '2026-09-01',
        next_maintenance: '2026-12-01',
        operating_hours: 8741,
        recommended_action: 'Filter replacement and glycol level check at next scheduled maintenance.',
        _demo: true,
      },
    },
    'ENV-01': {
      asset_id: 'ENV-01',
      station_id: 'maitri',
      name: 'Environmental Life Support Monitor',
      asset_type: 'environmental',
      status: 'NORMAL',
      temperature: 20.8,
      vibration: 0.1,
      current: 8,
      power: 5,
      fuel: 100,
      efficiency: 99,
      failure_risk: 5,
      operating_hours: 11042,
      last_update: '12:27:12 UTC+5',
      position: [4.5, 1.6, 0],
      maintenance: {
        state: 'NORMAL',
        last_maintenance: '2026-08-15',
        next_maintenance: '2027-02-15',
        operating_hours: 11042,
        recommended_action: 'Sensor calibration on schedule.',
        _demo: true,
      },
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // BHARATI STATION
  // ─────────────────────────────────────────────────────────────────────────
  bharati: {
    'GEN-01': {
      asset_id: 'GEN-01',
      station_id: 'bharati',
      name: 'Combined Heat & Power Turbine A',
      asset_type: 'generator',
      status: 'NORMAL',
      temperature: 78.6,
      vibration: 2.1,
      current: 82,
      power: 145,
      fuel: 85,
      efficiency: 91,
      failure_risk: 22,
      operating_hours: 5124,
      last_update: '12:27:12 UTC+5',
      position: [-5.0, 1.4, -2.0],
      maintenance: {
        state: 'NORMAL',
        last_maintenance: '2026-08-20',
        next_maintenance: '2026-11-20',
        operating_hours: 5124,
        recommended_action: 'Routine quarterly inspection on schedule.',
        _demo: true,
      },
    },
    'GEN-02': {
      asset_id: 'GEN-02',
      station_id: 'bharati',
      name: 'Combined Heat & Power Turbine B',
      asset_type: 'generator',
      status: 'NORMAL',
      temperature: 76.2,
      vibration: 1.9,
      current: 78,
      power: 140,
      fuel: 85,
      efficiency: 93,
      failure_risk: 18,
      operating_hours: 4892,
      last_update: '12:27:12 UTC+5',
      position: [-5.0, 1.4, 2.0],
      maintenance: {
        state: 'NORMAL',
        last_maintenance: '2026-08-20',
        next_maintenance: '2026-11-20',
        operating_hours: 4892,
        recommended_action: 'Routine quarterly inspection on schedule.',
        _demo: true,
      },
    },
    'BAT-01': {
      asset_id: 'BAT-01',
      station_id: 'bharati',
      name: 'Lithium Iron Phosphate Energy Storage',
      asset_type: 'battery',
      status: 'NORMAL',
      temperature: 22.1,
      vibration: 0.1,
      current: 65,
      power: 90,
      fuel: 92,
      efficiency: 97,
      failure_risk: 10,
      operating_hours: 3402,
      voltage: 52.8,
      last_update: '12:27:11 UTC+5',
      position: [-2.5, 1.0, -3.5],
      maintenance: {
        state: 'NORMAL',
        last_maintenance: '2026-07-01',
        next_maintenance: '2027-01-01',
        operating_hours: 3402,
        recommended_action: 'No action required.',
        _demo: true,
      },
    },
    'FUEL-01': {
      asset_id: 'FUEL-01',
      station_id: 'bharati',
      name: 'Double-Walled Cryo-Fuel System',
      asset_type: 'fuel_system',
      status: 'NORMAL',
      temperature: -18.4,
      vibration: 0.3,
      current: 15,
      power: 10,
      fuel: 81,
      efficiency: 99,
      failure_risk: 6,
      last_update: '12:27:09 UTC+5',
      position: [-8.0, 1.0, 0],
      maintenance: {
        state: 'NORMAL',
        last_maintenance: '2026-04-01',
        next_maintenance: '2026-10-01',
        operating_hours: 0,
        recommended_action: 'Tank integrity check due in 11 days.',
        _demo: true,
      },
    },
    'PUMP-01': {
      asset_id: 'PUMP-01',
      station_id: 'bharati',
      name: 'Seawater Reverse Osmosis Pump',
      asset_type: 'pump',
      status: 'CRITICAL',
      temperature: 91.4,
      vibration: 8.4,
      current: 52,
      power: 48,
      fuel: 100,
      efficiency: 58,
      failure_risk: 88,
      operating_hours: 4112,
      flow_rate: 12.4, // Severely degraded from nominal ~85 L/min
      last_update: '12:27:12 UTC+5',
      possible_issue: 'Severe cavitation and bearing thermal run-away',
      position: [3.2, 0.9, -3.0],
      maintenance: {
        state: 'IN_PROGRESS',
        last_maintenance: '2026-09-01',
        next_maintenance: null,
        operating_hours: 4112,
        known_issue: 'Bearing thermal runaway. Severe cavitation. Risk of seal failure imminent.',
        recommended_action: 'IMMEDIATE: Stop pump and inspect. Replace bearing assembly and impeller. Do not operate until cleared.',
        spare_parts: [
          { part_name: 'High-Temp Pump Bearing HTPB-80', part_code: 'BRG-HT-80', availability: 'OUT_OF_STOCK' },
          { part_name: 'Stainless Impeller SI-300', part_code: 'IMP-SS-300', availability: 'AVAILABLE' },
          { part_name: 'High-Temp Seal Cartridge', part_code: 'SEAL-HT-C', availability: 'UNKNOWN' },
        ],
        _demo: true,
      },
    },
    'HEATER-01': {
      asset_id: 'HEATER-01',
      station_id: 'bharati',
      name: 'Modulated District Glycol Loop',
      asset_type: 'hvac',
      status: 'NORMAL',
      temperature: 23.4,
      vibration: 0.6,
      current: 35,
      power: 52,
      fuel: 100,
      efficiency: 95,
      failure_risk: 14,
      operating_hours: 7218,
      last_update: '12:27:10 UTC+5',
      position: [2.0, 1.5, 2.5],
      maintenance: {
        state: 'NORMAL',
        last_maintenance: '2026-09-05',
        next_maintenance: '2026-12-05',
        operating_hours: 7218,
        recommended_action: 'Glycol concentration check at next service.',
        _demo: true,
      },
    },
    'ENV-01': {
      asset_id: 'ENV-01',
      station_id: 'bharati',
      name: 'Stilt Aerodynamic Air Quality Array',
      asset_type: 'environmental',
      status: 'NORMAL',
      temperature: 18.2,
      vibration: 0.2,
      current: 6,
      power: 4,
      fuel: 100,
      efficiency: 99,
      failure_risk: 4,
      operating_hours: 8934,
      last_update: '12:27:12 UTC+5',
      position: [5.0, 1.8, 0],
      maintenance: {
        state: 'NORMAL',
        last_maintenance: '2026-08-01',
        next_maintenance: '2027-02-01',
        operating_hours: 8934,
        recommended_action: 'Annual sensor replacement on schedule.',
        _demo: true,
      },
    },
  },
};

export function getStationDigitalTwinData(stationId: StationId): StationDigitalTwinData {
  const assets = INITIAL_STATION_ASSETS[stationId];
  const assetList = Object.values(assets);

  // Calculate average health from failure risks (100 - avg_risk)
  const avgRisk = assetList.reduce((acc, a) => acc + a.failure_risk, 0) / assetList.length;
  const calculatedHealth = Math.round(100 - avgRisk);

  return {
    station_id: stationId,
    station_name: stationId === 'bharati' ? 'BHARATI' : 'MAITRI',
    calculated_health_pct: calculatedHealth,
    assets,
  };
}
