/**
 * DAKSHIN — Command Type System
 * PC2 Remote Control Center
 *
 * These interfaces define the command contract between the frontend
 * and the future FastAPI command endpoint.
 *
 * Current implementation: FRONTEND DEMONSTRATION ONLY
 * Future implementation:  POST /api/commands  (PC2 FastAPI → MQTT → PC1)
 *
 * DO NOT add MQTT, safety-interlock, or actuator logic here.
 * Those belong to the backend and PC1 edge layer.
 */

import type { StationId } from './index';
import type { MachineAssetId } from './digitalTwin';

// ---------------------------------------------------------------------------
// Command Types
// ---------------------------------------------------------------------------

/** Commands that can be issued to actuator-capable assets. */
export type CommandType = 'START' | 'STOP';

/**
 * Full lifecycle of a command request.
 *
 * REQUESTED  → frontend has submitted the command
 * VALIDATING → backend/PC1 is checking safety preconditions
 * EXECUTING  → command has been forwarded to the actuator
 * COMPLETED  → actuator confirmed the state change
 * REJECTED   → safety validation refused the command (reason required)
 * FAILED     → command was accepted but execution failed (reason required)
 */
export type CommandStatus =
  | 'REQUESTED'
  | 'VALIDATING'
  | 'EXECUTING'
  | 'COMPLETED'
  | 'REJECTED'
  | 'FAILED';

// ---------------------------------------------------------------------------
// Request / Feedback Shapes
// ---------------------------------------------------------------------------

export interface CommandRequest {
  /** Unique command ID — UUID generated by the frontend */
  command_id: string;
  station_id: StationId;
  asset_id: MachineAssetId;
  command_type: CommandType;
  /** Who initiated — role label for demo; real auth token in production */
  requested_by: string;
  timestamp: string;
  /** Optional command-specific parameters (future extensibility) */
  parameters?: Record<string, unknown>;
}

export interface CommandFeedback {
  command_id: string;
  station_id: StationId;
  asset_id: MachineAssetId;
  /** Current status in the lifecycle */
  status: CommandStatus;
  /** Human-readable message or rejection reason */
  message: string;
  timestamp: string;
}

// ---------------------------------------------------------------------------
// Asset Commandability Rules
// ---------------------------------------------------------------------------

/**
 * Defines which asset types accept which commands.
 * Fuel tanks and environmental monitors are NOT actuators.
 *
 * Source of truth for the UI — controls which buttons are rendered.
 * Backend will enforce the same rules independently.
 */
export const ASSET_COMMANDS: Record<string, CommandType[]> = {
  generator: ['START', 'STOP'],
  pump:      ['START', 'STOP'],
  hvac:      ['START', 'STOP'],
  battery:   [],          // No direct commands defined yet
  fuel_system: [],        // Passive storage — not an actuator
  environmental: [],      // Sensor array — not an actuator
};

// ---------------------------------------------------------------------------
// User Roles (demo-only, frontend visibility gate)
// ---------------------------------------------------------------------------

export type UserRole = 'VIEWER' | 'OPERATOR' | 'ENGINEER' | 'ADMIN';

/** Roles that can submit operational commands */
export const COMMAND_ROLES: UserRole[] = ['OPERATOR', 'ENGINEER', 'ADMIN'];

/** Roles that can perform maintenance-record actions */
export const MAINTENANCE_ROLES: UserRole[] = ['ENGINEER', 'ADMIN'];
